server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /la-mystique-divine {
        return 301 /la-mystique-divine/;
    }

    location /la-mystique-divine/ {
        proxy_pass https://la-mystique-divine-production-1751.up.railway.app/;
        proxy_ssl_server_name on;
        proxy_set_header Host la-mystique-divine-production-1751.up.railway.app;
    }

    location = /humility {
        return 301 /humility/;
    }

    location /humility/ {
        proxy_pass https://humility-production.up.railway.app/;
        proxy_ssl_server_name on;
        proxy_set_header Host humility-production.up.railway.app;
    }
}
