server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /la-mystique-divine {
        return 301 /la-mystique-divine/;
    }

    location /la-mystique-divine/ {
        proxy_pass http://la-mystique-divine.railway.internal:8080/;
    }

    location = /humility {
        return 301 /humility/;
    }

    location /humility/ {
        proxy_pass http://humility.railway.internal:8080/;
    }
}
